# NUMPY ARRAYS
###### numpy arryas offers powerful library for numerical computing in python.
###### Homogenoues Data Type: numpy arrays contains.
###### Multidimensional: Arrays can have multiple dimensions 
###### Slicing and Indexing: Advanced slicing and indexing features.
###### Efficient Memory Usage: numpy arrays have a fixed size at creation.
###### Numpy arrays are a foundational tool for scientific computing in python.

In [8]:
# Import numpy library
import numpy as np


In [10]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [12]:
#create 1D numpy array
x = np.array([18,15,8,9])
print(x)
print(type(x))
print(x.dtype)

[18 15  8  9]
<class 'numpy.ndarray'>
int32


In [20]:
#Verify te data type in array
x = np.array([18.1,15,8,9])
print(x)
print(type(x))
print(x.dtype)

[18.1 15.   8.   9. ]
<class 'numpy.ndarray'>
float64


In [24]:
#Verify te data type in array
x = np.array(["R",15,8,9])
print(x)
print(type(x)) #u32 - uniocote string
print(x.dtype)

['R' '15' '8' '9']
<class 'numpy.ndarray'>
<U11


In [26]:
#create 1D numpy array
a2 = np.array([[18,15],[8,9]])
print(a2)
print(type(a2))
print(a2.shape)

[[18 15]
 [ 8  9]]
<class 'numpy.ndarray'>
(2, 2)


In [28]:
#reshaping an array 
a = np.array([18,15,8,9])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[18 15]
 [ 8  9]]
(2, 2)


In [30]:
#create an array with arange()
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [32]:
#use of around()
d = np.array([1.3496,2.654,3.25821])
print(d)
np.around(d,2)

[1.3496  2.654   3.25821]


array([1.35, 2.65, 3.26])

In [34]:
#use np.square root [np.sqrt()]
d = np.array([1.3496,2.654,3.25821])
print(d)
print(np.around(np.sqrt(d),2))

[1.3496  2.654   3.25821]
[1.16 1.63 1.81]


In [36]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [38]:
 #use of astype() to convert the data type
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [42]:
#Mathematical operations on rows and cols
a1 = np.array([[8,9,7],[6,5,4],[3,2,1]])
a1

array([[8, 9, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [50]:
a1.sum(axis=1) #sum of row

array([24, 15,  6])

In [52]:
a1.mean()

5.0

In [54]:
a1.sum(axis=0) #sum of vertices 

array([17, 16, 12])

In [58]:
#matrics operaations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [68]:
#making all diagonals zero 
#we can use fill diagonal function {fill_diagonal()}
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [70]:
#DEFINE TWO MATRICES AND MULTIPLY THEM 
A = np.array([[6,7,8],[2,9,3],[4,8,2]])
B = np.array([[2,6,2],[3,6,1],[2,5,2]])

#perforn matrix mulp
c = np.matmul(A,B)
print(c)

[[ 49 118  35]
 [ 37  81  19]
 [ 36  82  20]]


In [72]:
#Print the transpose of the matrices 
print(A.T)
print(B.T)

[[6 2 4]
 [7 9 8]
 [8 3 2]]
[[2 3 2]
 [6 6 5]
 [2 1 2]]


In [74]:
#ACCESING THE ARAY ELAMENTS
a4 = np.array([[6,7,8],[2,9,3],[4,8,2],[0,2,7]])
a4

array([[6, 7, 8],
       [2, 9, 3],
       [4, 8, 2],
       [0, 2, 7]])

In [90]:
a4[3][1]

2

In [112]:
a4[1:3,0:]

array([[2, 9, 3],
       [4, 8, 2]])

In [114]:
# ACCESSING MAX VALUE AND ITS INDEX
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [120]:
print(np.argmax(a3, axis = 1)) #np.amax gives the max element
print(np.argmax(a3, axis = 0)) #np.argmax gives the max element index

[2 2 0]
[2 0 1]


In [122]:
print(np.amax(a3, axis = 1))
print(np.amax(a3, axis = 0))

[5 8 9]
[9 4 8]
