# Pandas
### Important Features of pandas :-
##### Supports datastructures 
##### Data cleaning : supports missing data with methods like fill
##### Indexing and slicing : Offers robusst label-based and position based ind
##### Data Aggregation : Includes built-iin function for group operations via
##### Data Transformation : Facultates reshaping, pivoting of datasets 
##### Time Series Handling : Bulit-in suports for time-series data with date-ra
##### Data Visualization : Integarte with Mathplotib for quick plotting of data 
##### File I/O : Suports reading and writing data in multiple formats, including 


## CREATE PANDAS SERIES (it is size immuatble)

In [3]:
#IMPORT PANDAS
import pandas as pd

In [5]:
#create pandas series using list

data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [9]:
#create pandas series using list

data = [10,20,30,40.22]
series = pd.Series(data)
print(series)

0    10.00
1    20.00
2    30.00
3    40.22
dtype: float64


In [12]:
#create pandas series using list

data = [10,20,30,"A"]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3     A
dtype: object


In [14]:
##create a series using a custom index
data = [1,2,3,4]
i = ['A','B','C','D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [18]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [22]:
#CREATE PANDAS USING DICTIONARY 
data = {'a': 10, 'b': 20,'c': 30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [34]:
#CREATE PANDAS USING DICTIONARY 
data = {'a': 10, 'b': 100,'c': 30} #series have replace method
series.replace(20,100)
print(series)

a      10
b      20
c    Ammu
dtype: object


In [28]:
#CREATE PANDAS USING DICTIONARY 
data = {'a': 10, 'b': 20,'c': "Ammu"}
series = pd.Series(data)
print(series)

a      10
b      20
c    Ammu
dtype: object


In [36]:
#CREATE SERIES USING NUMPY ARRAY
import numpy as np

data = np.array([100,300,3000])
series = pd.Series(data, index=['a','b','c'])
print(series)

a     100
b     300
c    3000
dtype: int32


# PANDAS DATAFRAME

In [38]:
#CREATE PANDAS DATAFRAME FROM DICTIONARY OF LISTS 
import pandas as pd

data = {'Name':['Alice','Bob','Mary'], 'Age':[25,15,10],'Country':['USA','PARIS','AUS']}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   15   PARIS
2   Mary   10     AUS


In [53]:
#CREATE PANDAS DATAFRAME FROM NUMPY ARRAY 
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns = ['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [55]:
#CREATE A DATAAFRAME FROM A NESTED LIST
data = [[1, 'Alice',25],[2,'Bob',30],[3,'Marry',34]]
print(data)
df = pd.DataFrame(data, columns = ['ID','Name','Age'])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 30], [3, 'Marry', 34]]
   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
2   3  Marry   34


In [59]:
#IMPORTING XL FILE TO NUMPY PANDAS 
iris_df = pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


RangeIndex(start=0, stop=150, step=1)

In [64]:
#Import data frame from an excel file 
iris_df = pd.read_excel("iris.xlsx")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]
